/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcceleratorRouteImport } from './routes/accelerator'
import { Route as AccountStatusRouteImport } from './routes/account-status'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as WaitingListRouteImport } from './routes/waiting-list'
import { Route as AuthenticatedPortalRouteImport } from './routes/_authenticated/portal'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminInstructorRouteImport } from './routes/admin.instructor'
import { Route as AdminSubmissionsRouteImport } from './routes/admin.submissions'
import { Route as SyllabusCourseSlugRouteImport } from './routes/syllabus.$courseSlug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceleratorRoute = AcceleratorRouteImport.update({
  id: '/accelerator',
  path: '/accelerator',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountStatusRoute = AccountStatusRouteImport.update({
  id: '/account-status',
  path: '/account-status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitingListRoute = WaitingListRouteImport.update({
  id: '/waiting-list',
  path: '/waiting-list',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortalRoute = AuthenticatedPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInstructorRoute = AdminInstructorRouteImport.update({
  id: '/admin/instructor',
  path: '/admin/instructor',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSubmissionsRoute = AdminSubmissionsRouteImport.update({
  id: '/admin/submissions',
  path: '/admin/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SyllabusCourseSlugRoute = SyllabusCourseSlugRouteImport.update({
  id: '/syllabus/$courseSlug',
  path: '/syllabus/$courseSlug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accelerator': typeof AcceleratorRoute
  '/account-status': typeof AccountStatusRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/waiting-list': typeof WaitingListRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/instructor': typeof AdminInstructorRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/syllabus/$courseSlug': typeof SyllabusCourseSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accelerator': typeof AcceleratorRoute
  '/account-status': typeof AccountStatusRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/waiting-list': typeof WaitingListRoute
  '/portal': typeof AuthenticatedPortalRoute
  '/admin/instructor': typeof AdminInstructorRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/syllabus/$courseSlug': typeof SyllabusCourseSlugRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/accelerator': typeof AcceleratorRoute
  '/account-status': typeof AccountStatusRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verify-email': typeof VerifyEmailRoute
  '/waiting-list': typeof WaitingListRoute
  '/_authenticated/portal': typeof AuthenticatedPortalRoute
  '/admin/instructor': typeof AdminInstructorRoute
  '/admin/submissions': typeof AdminSubmissionsRoute
  '/syllabus/$courseSlug': typeof SyllabusCourseSlugRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accelerator'
    | '/account-status'
    | '/apply'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-email'
    | '/waiting-list'
    | '/portal'
    | '/admin/instructor'
    | '/admin/submissions'
    | '/syllabus/$courseSlug'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accelerator'
    | '/account-status'
    | '/apply'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-email'
    | '/waiting-list'
    | '/portal'
    | '/admin/instructor'
    | '/admin/submissions'
    | '/syllabus/$courseSlug'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/accelerator'
    | '/account-status'
    | '/apply'
    | '/auth'
    | '/checkout'
    | '/contact'
    | '/courses'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verify-email'
    | '/waiting-list'
    | '/_authenticated/portal'
    | '/admin/instructor'
    | '/admin/submissions'
    | '/syllabus/$courseSlug'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AcceleratorRoute: typeof AcceleratorRoute
  AccountStatusRoute: typeof AccountStatusRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WaitingListRoute: typeof WaitingListRoute
  AdminInstructorRoute: typeof AdminInstructorRoute
  AdminSubmissionsRoute: typeof AdminSubmissionsRoute
  SyllabusCourseSlugRoute: typeof SyllabusCourseSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accelerator': {
      id: '/accelerator'
      path: '/accelerator'
      fullPath: '/accelerator'
      preLoaderRoute: typeof AcceleratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-status': {
      id: '/account-status'
      path: '/account-status'
      fullPath: '/account-status'
      preLoaderRoute: typeof AccountStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/waiting-list': {
      id: '/waiting-list'
      path: '/waiting-list'
      fullPath: '/waiting-list'
      preLoaderRoute: typeof WaitingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portal': {
      id: '/_authenticated/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof AuthenticatedPortalRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/instructor': {
      id: '/admin/instructor'
      path: '/admin/instructor'
      fullPath: '/admin/instructor'
      preLoaderRoute: typeof AdminInstructorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/submissions': {
      id: '/admin/submissions'
      path: '/admin/submissions'
      fullPath: '/admin/submissions'
      preLoaderRoute: typeof AdminSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/syllabus/$courseSlug': {
      id: '/syllabus/$courseSlug'
      path: '/syllabus/$courseSlug'
      fullPath: '/syllabus/$courseSlug'
      preLoaderRoute: typeof SyllabusCourseSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedPortalRoute: typeof AuthenticatedPortalRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedPortalRoute: AuthenticatedPortalRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AcceleratorRoute: AcceleratorRoute,
  AccountStatusRoute: AccountStatusRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WaitingListRoute: WaitingListRoute,
  AdminInstructorRoute: AdminInstructorRoute,
  AdminSubmissionsRoute: AdminSubmissionsRoute,
  SyllabusCourseSlugRoute: SyllabusCourseSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
